#include <catch2/catch_test_macros.hpp>

#include "pgm/control/Dispatcher.hpp"

#include "Moira.h"

#include <miniz.h>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

// The SingleStepTests 68000 suite (https://github.com/SingleStepTests/680x0),
// run against Moira as the machine configures it: every instruction from a
// random state, compared with the final state, the memory and the cycle count.
// scripts/fetch-680x0-tests.sh downloads the suite; without it these skip.

using Json = nlohmann::json;

namespace
{

// Where Moira and the suite disagree, outside address errors, as measured on
// suite commit e0d5ece. The suite is generated by an emulator; Moira is checked
// against a real 68000 with cputester. Every case is an edge the PGM's software
// does not reach: shift counts beyond the operand's width (ASR, ASL), flags the
// manual leaves undefined (CHK, DIVS, DIVU), the timing of ADDQ/SUBQ.l to an
// address register and of BTST on an immediate, and LINK on A7. Which side fx68k,
// the RTL's 68000, takes is open (docs/open-questions.md). The counts are held
// so that a change to Moira that moves any of them is noticed.
std::map<std::string, std::size_t> const& knownDisagreements()
{
  static std::map<std::string, std::size_t> const COUNTS{
    { "ADD.l.json.gz", 380 },  { "ASL.b.json.gz", 2 },   { "ASR.b.json.gz", 1642 }, { "ASR.l.json.gz", 1031 },
    { "ASR.w.json.gz", 1063 }, { "BTST.json.gz", 138 },  { "CHK.json.gz", 321 },    { "DIVS.json.gz", 3146 },
    { "DIVU.json.gz", 1855 },  { "LINK.json.gz", 1005 }, { "SUB.l.json.gz", 351 },
  };
  return COUNTS;
}

std::filesystem::path suiteDirectory()
{
  return PGM_TEST_680X0_DIR;
}

/// A 68000 on a bare 24-bit bus of RAM, which is what each test describes.
class TestCpu : public moira::Moira
{
public:
  std::unordered_map<std::uint32_t, std::uint8_t> memory;

  /// Whether the last instruction raised an address error.
  bool addressError{};

  void setPrefetch( std::uint16_t ird, std::uint16_t irc )
  {
    queue.ird = ird;
    queue.irc = irc;
  }

protected:
  void willExecute( moira::M68kException raised, moira::u16 /*vector*/ ) override
  {
    addressError = addressError || raised == moira::M68kException::ADDRESS_ERROR;
  }

  [[nodiscard]] moira::u8 read8( moira::u32 addr ) const override
  {
    auto const found = memory.find( addr & 0xffffffU );
    return found == memory.end() ? 0 : found->second;
  }

  [[nodiscard]] moira::u16 read16( moira::u32 addr ) const override
  {
    return static_cast<moira::u16>( ( read8( addr ) << 8U ) | read8( addr + 1 ) );
  }

  [[nodiscard]] moira::u32 read32( moira::u32 addr ) const override
  {
    return ( static_cast<moira::u32>( read16( addr ) ) << 16U ) | read16( addr + 2 );
  }

  void write8( moira::u32 addr, moira::u8 val ) const override
  {
    // Moira's client interface is const; the memory is the test's own.
    const_cast<TestCpu*>( this )->memory[addr & 0xffffffU] = val; // NOLINT(cppcoreguidelines-pro-type-const-cast)
  }

  void write16( moira::u32 addr, moira::u16 val ) const override
  {
    write8( addr, static_cast<moira::u8>( val >> 8U ) );
    write8( addr + 1, static_cast<moira::u8>( val ) );
  }

  void write32( moira::u32 addr, moira::u32 val ) const override
  {
    write16( addr, static_cast<moira::u16>( val >> 16U ) );
    write16( addr + 2, static_cast<moira::u16>( val ) );
  }
};

/// The content of a .json.gz file: gzip's header, then raw deflate.
std::string gunzip( std::filesystem::path const& path )
{
  std::ifstream stream{ path, std::ios::binary };
  std::vector<std::uint8_t> const packed{ std::istreambuf_iterator<char>{ stream }, std::istreambuf_iterator<char>{} };
  REQUIRE( packed.size() > 18 );
  REQUIRE( packed[0] == 0x1f );
  REQUIRE( packed[1] == 0x8b );

  // RFC 1952: a 10-byte header, then the optional fields its flags announce.
  std::uint8_t const flags = packed[3];
  std::size_t at = 10;
  if ( ( flags & 0x04U ) != 0 )
  {
    at += 2 + static_cast<std::size_t>( packed[at] | ( packed[at + 1] << 8U ) );
  }
  for ( std::uint8_t const terminated : { std::uint8_t{ 0x08 }, std::uint8_t{ 0x10 } } )
  {
    if ( ( flags & terminated ) != 0 )
    {
      while ( packed[at] != 0 )
      {
        ++at;
      }
      ++at;
    }
  }
  if ( ( flags & 0x02U ) != 0 )
  {
    at += 2;
  }

  std::size_t size = 0;
  void* const text = tinfl_decompress_mem_to_heap( packed.data() + at, packed.size() - at, &size, 0 );
  REQUIRE( text != nullptr );
  std::string result{ static_cast<char const*>( text ), size };
  mz_free( text );
  return result;
}

void load( TestCpu& cpu, Json const& state )
{
  for ( int i = 0; i < 8; ++i )
  {
    cpu.setD( i, state.at( "d" + std::to_string( i ) ).get<std::uint32_t>() );
  }
  for ( int i = 0; i < 7; ++i )
  {
    cpu.setA( i, state.at( "a" + std::to_string( i ) ).get<std::uint32_t>() );
  }
  // The status register decides which of the two stack pointers is A7, so it
  // goes first, with both pointers set again after it.
  cpu.setSR( state.at( "sr" ).get<std::uint16_t>() );
  cpu.setUSP( state.at( "usp" ).get<std::uint32_t>() );
  cpu.setISP( state.at( "ssp" ).get<std::uint32_t>() );
  cpu.setPC( state.at( "pc" ).get<std::uint32_t>() );
  cpu.setPC0( state.at( "pc" ).get<std::uint32_t>() );
  auto const& prefetch = state.at( "prefetch" );
  cpu.setPrefetch( prefetch.at( 0 ).get<std::uint16_t>(), prefetch.at( 1 ).get<std::uint16_t>() );
  cpu.memory.clear();
  for ( auto const& cell : state.at( "ram" ) )
  {
    cpu.memory[cell.at( 0 ).get<std::uint32_t>()] = cell.at( 1 ).get<std::uint8_t>();
  }
}

/// What differs between `cpu` after the instruction and the test's final
/// state, or nothing.
std::optional<std::string>
mismatch( TestCpu const& cpu, Json const& expected, std::int64_t cycles, std::int64_t length )
{
  std::ostringstream out;
  auto const check = [&]( std::string const& name, std::uint32_t actual )
  {
    auto const wanted = expected.at( name ).get<std::uint32_t>();
    if ( actual != wanted )
    {
      out << name << " " << std::hex << actual << " != " << wanted << "; ";
    }
  };
  for ( int i = 0; i < 8; ++i )
  {
    check( "d" + std::to_string( i ), cpu.getD( i ) );
  }
  for ( int i = 0; i < 7; ++i )
  {
    check( "a" + std::to_string( i ), cpu.getA( i ) );
  }
  check( "usp", cpu.getUSP() );
  check( "ssp", cpu.getISP() );
  check( "sr", cpu.getSR() );
  check( "pc", cpu.getPC() );
  for ( auto const& cell : expected.at( "ram" ) )
  {
    auto const address = cell.at( 0 ).get<std::uint32_t>();
    auto const found = cpu.memory.find( address );
    std::uint8_t const actual = found == cpu.memory.end() ? 0 : found->second;
    if ( actual != cell.at( 1 ).get<std::uint8_t>() )
    {
      out << "ram[" << std::hex << address << "] " << int{ actual } << " != " << cell.at( 1 ).get<int>() << "; ";
    }
  }
  if ( cycles != length )
  {
    out << "cycles " << std::dec << cycles << " != " << length << "; ";
  }
  std::string const text = out.str();
  return text.empty() ? std::nullopt : std::optional<std::string>{ text };
}

} // namespace

TEST_CASE( "Moira passes the SingleStepTests 68000 suite", "[cpu-suite]" )
{
  std::vector<std::filesystem::path> files;
  std::error_code failed;
  for ( auto const& entry : std::filesystem::directory_iterator( suiteDirectory(), failed ) )
  {
    if ( entry.path().string().ends_with( ".json.gz" ) )
    {
      files.push_back( entry.path() );
    }
  }
  if ( files.empty() )
  {
    SKIP( "no suite in " << suiteDirectory() << "; fetch it with scripts/fetch-680x0-tests.sh" );
  }
  std::ranges::sort( files );

  TestCpu cpu;
  std::ostringstream report;
  std::size_t total = 0;
  std::size_t passed = 0;
  std::size_t addressErrorFailures = 0;
  bool unexpected = false;
  for ( auto const& file : files )
  {
    Json const tests = Json::parse( gunzip( file ) );
    std::size_t failedHere = 0;
    std::string firstFailure;
    for ( auto const& test : tests )
    {
      load( cpu, test.at( "initial" ) );
      cpu.addressError = false;
      std::int64_t const before = cpu.getClock();
      cpu.execute();
      auto const problem =
          mismatch( cpu, test.at( "final" ), cpu.getClock() - before, test.at( "length" ).get<std::int64_t>() );
      ++total;
      if ( problem && cpu.addressError )
      {
        ++addressErrorFailures;
      }
      else if ( problem )
      {
        if ( failedHere++ == 0 )
        {
          firstFailure = test.at( "name" ).get<std::string>() + ": " + *problem;
        }
      }
      else
      {
        ++passed;
      }
    }
    auto const known = knownDisagreements().find( file.filename().string() );
    std::size_t const expected = known == knownDisagreements().end() ? 0 : known->second;
    if ( failedHere != expected )
    {
      report << file.filename().string() << ": " << failedHere << " of " << tests.size() << " fail where " << expected
             << " are known to, first " << firstFailure << "\n";
      unexpected = true;
    }
  }
  // Address errors are not held to the suite: the PGM's software does not raise
  // them, and the suite and Moira stack their frames differently.
  INFO( report.str() << passed << " of " << total << " pass; " << addressErrorFailures
                     << " of the failures raise an address error" );
  CHECK_FALSE( unexpected );
}
